### ISSUE TITLE
Need help on Fuzzy q learning

### ISSUE THREAD

**Issue by cartelgouabou** [pooyanjamshidi/Fuzzy-Q-Learning#1]
Hello,
my name is FOAHOM Arthur Cartel, I am a student at the Faculty of Industrial Engineering of the University of Douala in Cameroon, I am working for my final project on the design of a robot for the " avoidance of obstacle based on a fuzzy q learning controller, I have already completed the establishment of all the rules, all the parameters of reinforcement and other, but I have difficulty to make simulations on matlab, can you help me?

**Comment by cartelgouabou** [comment]
I can not download the demo code to test it on my machine

**Comment by pooyanjamshidi** [comment]
@gouabou93 we had some conversation over email, so I presume you now could download the demo code and run it. So, I'm closing this issue. Thanks.
